---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Run minio as docker container
    shell: docker run -d -p 9000:9000 --name minio1 -v /mnt/data:/data -v /mnt/config:/root/.minio minio/minio server /data
